server:
  port: 8080

spring:
  application:
    name: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: dnatestingnotification@gmail.com
    password: ugltgfcsfppohwam
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  websocket:
    sockjs:
      enabled: true
      client-library-url: https://cdn.jsdelivr.net/npm/sockjs-client@1/dist/sockjs.n.js
  thymeleaf:
    cache: false
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/dna_testing_system}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:12345}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    springframework.web: DEBUG
    springframework.web.socket: DEBUG
    springframework.security: DEBUG
application:
  base-url: "http://localhost:8080/index"

identity:
  jwt:
    secret-key: ${JWT_SECRET_KEY:cb3f30b0ec715f1bcbead50dc9d77786c038b569f2f6adb9a9e724e07ffd6c17}
    token-exp: PT15M # 15 minutes
    refresh-token-exp: P1D # 1 day

mail:
  sender:
    from: ${MAIL_SENDER_FROM:dnatestingnotification@gmail.com}
