name: Deploy API Service to AWS
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: repoName
  CONTAINER_NAME: containerName

jobs:
  build-test-sonar:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1